// Xiyue Suo, NUID: 001348347
// Assignment #1, INFO5100, 09/30/2020

package Interface;
import Person.Info;
import Person.InfoHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * This class creates a panel to view profiles.
 * @author suoxiyue
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private InfoHistory ih;
    public ViewJPanel(InfoHistory ih) {
        initComponents();
        this.ih = ih;
        populateTable();
    }
    
    // This method will pop the profile table
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel)tblInfo.getModel();
        dtm.setRowCount(0);
        for (Info i: ih.getInfoHistory()) {
            Object row[] = new Object[2];
            row[0] = i;
            row[1] = i.getBirthday();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLinkedIn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtProtocol = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBiometric = new javax.swing.JTextField();
        code = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtVehicle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        txtDevice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMedicalNum = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        health = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHealth = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        txtLinkedIn.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel11.setText("Protocol Address");

        txtProtocol.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel12.setText("Biometric Identifier");

        txtBiometric.setEnabled(false);

        code.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        code.setText("Personal Code");

        jLabel3.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel3.setText("Geographic Data");

        jLabel14.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel14.setText("Vehicle(Plate#)");

        txtCode.setEnabled(false);

        txtGeoData.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        txtGeoData.setEnabled(false);

        txtVehicle.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel4.setText("Date of Birth");

        jLabel15.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel15.setText("Device(serial#)");

        jLabel1.setFont(new java.awt.Font("Luminari", 1, 24)); // NOI18N
        jLabel1.setText("View Profile");
        jLabel1.setToolTipText("");

        txtBirthday.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        txtBirthday.setEnabled(false);

        txtDevice.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel2.setText("Name");

        jLabel5.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel5.setText("Telephone");

        txtBank.setEnabled(false);

        txtName.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        txtName.setEnabled(false);

        txtTelephone.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        txtTelephone.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel16.setText("Medical Record#");

        jLabel6.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel6.setText("Fax");

        txtMedicalNum.setEnabled(false);

        txtFax.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        txtFax.setEnabled(false);

        health.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        health.setText("Health Plan#");

        jLabel7.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel7.setText("Email");

        txtHealth.setEnabled(false);

        txtEmail.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        txtEmail.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel8.setText("SSN");

        jLabel18.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel18.setText("photo");

        jLabel19.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel19.setText("Bank Account#");

        txtSSN.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        txtSSN.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel9.setText("License#");

        jLabel10.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        jLabel10.setText("LinkedIn");

        txtLicense.setEnabled(false);

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Birthday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInfo);

        btnViewDetails.setBackground(new java.awt.Color(0, 204, 51));
        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        image.setFont(new java.awt.Font("LiSong Pro", 1, 13)); // NOI18N
        image.setForeground(new java.awt.Color(204, 0, 51));
        image.setText("No Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBirthday)
                                    .addComponent(txtName)
                                    .addComponent(txtTelephone)
                                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGeoData)
                                    .addComponent(txtSSN))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(health)
                                    .addComponent(code)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(186, 186, 186)
                                .addComponent(btnViewDetails)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBank, txtBiometric, txtCode, txtDevice, txtHealth, txtLicense, txtLinkedIn, txtMedicalNum, txtProtocol, txtVehicle});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBirthday, txtEmail, txtFax, txtGeoData, txtName, txtSSN, txtTelephone});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewDetails)
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtMedicalNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(health)
                            .addComponent(txtHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(code)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBank, txtBiometric, txtCode, txtDevice, txtHealth, txtLicense, txtLinkedIn, txtMedicalNum, txtProtocol, txtVehicle});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBirthday, txtEmail, txtFax, txtGeoData, txtName, txtSSN, txtTelephone});

    }// </editor-fold>//GEN-END:initComponents

    // This method will show the details of stored profile when view details
    // button clicked
    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // find the selected profile and retrieve from history
        int selectedRow = tblInfo.getSelectedRow();
        if(selectedRow >= 0) {
            Info i = (Info)tblInfo.getValueAt(selectedRow, 0);
            image.setIcon(i.getPhoto());
            txtName.setText(i.getName());
            txtGeoData.setText(i.getGeographicData());
            txtBirthday.setText(i.getBirthday());
            txtTelephone.setText(String.valueOf(i.getTelephone()));
            txtFax.setText(String.valueOf(i.getFax()));
            txtEmail.setText(String.valueOf(i.getEmail()));
            txtSSN.setText(String.valueOf(i.getSsn()));
            txtMedicalNum.setText(String.valueOf(i.getMedicalRecordNum()));
            txtHealth.setText(String.valueOf(i.getHealthPlanNum()));
            txtBank.setText(String.valueOf(i.getBankAccountNum()));
            txtLicense.setText(i.getLicense());
            txtVehicle.setText(i.getVehicle());
            txtDevice.setText(i.getDevice());
            txtLinkedIn.setText(i.getLinkedIn());
            txtProtocol.setText(i.getProtocolAddress());
            txtBiometric.setText(i.getBioIndentifier());
            txtCode.setText(i.getPersonalCode());
        } else {
            // pop the notice when no row was selected
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    // This method will deleted a profile
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int selectedRow = tblInfo.getSelectedRow();
        if(selectedRow >= 0) {
            Info i = (Info)tblInfo.getValueAt(selectedRow, 0);
            ih.deleteInfo(i);
            JOptionPane.showMessageDialog(null, "Information has been deleted");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        
        // set the text field empty when the profile deleted
        image.setIcon(null);
        txtName.setText("");
        txtGeoData.setText("");
        txtBirthday.setText("");
        txtTelephone.setText("");
        txtFax.setText("");
        txtEmail.setText("");
        txtSSN.setText("");
        txtMedicalNum.setText("");
        txtHealth.setText("");
        txtBank.setText("");
        txtLicense.setText("");
        txtVehicle.setText("");
        txtDevice.setText("");
        txtLinkedIn.setText("");
        txtProtocol.setText("");
        txtBiometric.setText("");
        txtCode.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel code;
    private javax.swing.JLabel health;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtBiometric;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDevice;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealth;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProtocol;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables
}
